image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  only:
    - master
  script:
    - "rm ./src/main/resources/application.properties"
    - "mv ./src/main/resources/application.properties.prod ./src/main/resources/application.properties"
    - "mvn package -B"

  artifacts:
    paths:
      - target/*.jar

docker-build:
  image: docker:latest
  stage: package
  only:
    - master
  before_script:
    - apk add --no-cache curl jq py-pip
    - pip install awscli
    - export AWS_ACCESS_KEY_ID=AKIA2X6WEGJ332AUPXQG
    - export AWS_SECRET_ACCESS_KEY=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
  script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - docker build -t 738646569591.dkr.ecr.us-east-1.amazonaws.com/backend .
    - docker push 738646569591.dkr.ecr.us-east-1.amazonaws.com/backend

ecs-deploy:
  image: python:latest
  stage: deploy
  only:
    - master
  before_script:
    - pip install awscli
    - export AWS_ACCESS_KEY_ID=AKIA2X6WEGJ332AUPXQG
    - export AWS_SECRET_ACCESS_KEY=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
  script:
    - aws ecs register-task-definition --region  us-east-1 --cli-input-json file://deploy.json >> temp.json
    - REV=`grep  '"revision"' temp.json | awk '{print $2}' | sed -e 's/,//'`
    - echo $REV
    - aws ecs update-service --cluster DivorcioOnline --service backend --task-definition backend:${REV} --region us-east-1
